{
 "title": "Pedidos API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Pedidos criados",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 5 },
   "targets": [
    { "expr": "sum(pedidos_criados_total)" }
   ]
  },
  {
   "title": "Pagamentos confirmados",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 5 },
   "targets": [
    { "expr": "sum(pedidos_pagos_total)" }
   ]
  },
  {
   "title": "Requisições por segundo por status",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latência p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Requisições em andamento",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 5 },
   "targets": [
    { "expr": "sum(http_requests_in_progress)" }
   ]
  }
 ]
}